IPT_101/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPT_101.Models;
using IPT_101.Repository;
using IPT_101.Repository.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IPT_101.Controllers
{
    public class LoginController : Controller
    {
        private readonly IPT_101Context _context;

        public LoginController(IPT_101Context context)
        {
            _context = context;
        }

        db dbop = new db();
        // GET: LoginController
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> IndexAsync([Bind] Login login)
        {
            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Email == login.Email);
            int res = dbop.LogInCheck(login);
            if (res == 1)
            {
                TempData["msg"] = "Welcome customer";
                ViewBag.User = user;
                return View(user);

                //return RedirectToAction("Index", "Myaccount");
            }
            else
            {
                TempData["msg"] = "Email or Password is wrong!";
            }


            return View();
        }


        // GET: LoginController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LoginController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoginController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LoginController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoginController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

IPT_101/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IPT_101.Repository;
using IPT_101.Repository.Models;
using cloudscribe.Pagination.Models;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace IPT_101.Controllers
{

    public class ProductsController : Controller
    {
        private readonly IPT_101Context _context;

        public ProductsController(IPT_101Context context)
        {
           var result = _context = context;
        }

        public PartialViewResult SearchProducts(string searchText, int pageNumber = 1, int pageSize = 10)
        {
           
            int ExcludeRecords = (pageSize * pageNumber) - pageSize;
            var iPT_101Context = from b in _context.ProductDetails.Include(p => p.Product).Include(p => p.ProductType)
                                 select b;
            if (!String.IsNullOrEmpty(searchText))
            {
                iPT_101Context = iPT_101Context.Where(b => b.Product.ProductName.Contains(searchText));
            }
            
            iPT_101Context = iPT_101Context = iPT_101Context
                .Skip(ExcludeRecords)
                .Take(pageSize);
            return PartialView("_GridView", iPT_101Context);
        }
        // GET: Products
        public IActionResult Index2()
        {
            //var iPT_101Context = _context.ProductDetails.Include(p => p.Product).Include(p => p.ProductType);
            return View();
        }
        
        public async Task<IActionResult> Index(string searchString,string sortOrder,int pageNumber = 1, int pageSize = 10)
        {
            List<ProductType> productTypes = new List<ProductType>();
            productTypes = (from ProductType in _context.ProductTypes
                            select ProductType).ToList();

            ViewBag.ListOfCategory = productTypes;
            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.DefaultSortParam = "";
            ViewBag.PriceDescSortParam ="price_desc" ;
            ViewBag.PriceAscSortParam = "price_asc" ;
            ViewBag.TotalItems = _context.ProductDetails.Count();
            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            int ExcludeRecords = (pageSize * pageNumber) - pageSize;
            //String.IsNullOrEmpty(sortOrder) ? "price_desc": "";
            var iPT_101Context = from b in _context.ProductDetails.Include(p => p.Product).Include(p => p.ProductType)
                                 select b;

            //var shoppingcart = await _context.ShoppingCarts
                //.Include(p => p.Product)
                //.Include(p => p.User)
                //.FirstOrDefaultAsync(m => m.Id == id);
                

            //Sorting Logic
            switch (sortOrder)
            {
                case "price_desc":
                    iPT_101Context = iPT_101Context.OrderByDescending(b => b.Product.SuggestedUnitPrice);
                    break;
                case "price_asc":
                    iPT_101Context = iPT_101Context.OrderBy(b => b.Product.SuggestedUnitPrice);
                    break;
                default:
                    iPT_101Context = _context.ProductDetails.Include(p => p.Product).Include(p => p.ProductType);
                    break;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                iPT_101Context = iPT_101Context.Where(b => b.Product.ProductName.Contains(searchString));
            }
            
            iPT_101Context = iPT_101Context
                .Skip(ExcludeRecords)
                .Take(pageSize);
            
            var result = new PagedResult<ProductDetail>
            {
                Data = iPT_101Context.AsNoTracking().ToList(),
                TotalItems = _context.ProductDetails.Count(),
                PageNumber = pageNumber,
                PageSize = pageSize
                

            };
            
            var options = new JsonSerializerOptions()
            {
                ReferenceHandler = ReferenceHandler.Preserve
            };
            var objstr = JsonSerializer.Serialize(result, options);
            ViewBag.ListOfProducts = objstr;

            ViewBag.Data = iPT_101Context.AsNoTracking().ToList();

            //ViewBag.ShoppingCart = shoppingcart;
            return View(result);
        }
        [HttpPost]
         //need tanggalin to 
        public async Task<IActionResult> Index(int ProductId, int ProductTypeId, int UserId, int UnitPrice, int TotalPrice, int Quantity, ShoppingCart shoppingCart, int id = 0)
        {
            //may mali pa kapag nag start tayo uli ng bagong session di dumadagdag sa latest cart

            var ser = await _context.ShoppingCarts.OrderByDescending(c => c.Id).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                var result = new ShoppingCart();

                if(ser == null || shoppingCart == null)
                {
                    result.Id = 0;
                    result.ProductDetailsId = ProductId;
                    result.ProductId = ProductId;
                    result.UserId = UserId;
                    result.ProductTypeId = ProductTypeId;
                    result.UnitPrice = UnitPrice;
                    result.TotalPrice = TotalPrice;
                    result.Quantity = Quantity;
                    _context.Add(result);
                    await _context.SaveChangesAsync();
                    
                    ViewData["cartcount"] = _context.ShoppingCarts.Count();
                    ViewBag.CartCount = ViewData["cartcount"];
                    return RedirectToAction(nameof(Index));
                }
                else if(ser != null || shoppingCart != null)
                {
                    shoppingCart = (ShoppingCart) await _context.ShoppingCarts.Where(predicate: p => p.UserId == UserId).FirstOrDefaultAsync(p => p.ProductId == ProductId);

                    if (ser.UserId == UserId && ser.ProductId == ProductId)
                    {

                        
                        //var ito = shop.ShoppingCarts.Find(UserId);
                        //null daw si ito.totalprice
                        //ito.TotalPrice = TotalPrice + TotalPrice;
                        //shop.Entry(ito).CurrentValues.SetValues(TotalPrice);
                        shoppingCart.Id = shoppingCart.Id;
                        shoppingCart.ProductDetailsId = ProductId;
                        shoppingCart.ProductId = ProductId;
                        shoppingCart.UserId = UserId;
                        shoppingCart.ProductTypeId = ProductTypeId;
                        shoppingCart.UnitPrice = UnitPrice;
                        shoppingCart.TotalPrice = shoppingCart.TotalPrice + TotalPrice;
                        shoppingCart.Quantity = shoppingCart.Quantity + Quantity;
                        
                        await _context.SaveChangesAsync();
                        ViewData["cartcount"] = _context.ShoppingCarts.Count();
                        ViewBag.CartCount = ViewData["cartcount"];
                        return RedirectToAction(nameof(Index));
                        //_context.Entry(shoppingCart).State = EntityState.Unchanged;
                        //_context.Attach(shoppingCart);
                        //shoppingCart.TotalPrice = TotalPrice + TotalPrice;

                    }else if (shoppingCart != null)
                    {
                        shoppingCart.Id = shoppingCart.Id;
                        shoppingCart.ProductDetailsId = ProductId;
                        shoppingCart.ProductId = ProductId;
                        shoppingCart.UserId = UserId;
                        shoppingCart.ProductTypeId = ProductTypeId;
                        shoppingCart.UnitPrice = UnitPrice;
                        shoppingCart.TotalPrice = shoppingCart.TotalPrice + TotalPrice;
                        shoppingCart.Quantity = shoppingCart.Quantity + Quantity;
                        await _context.SaveChangesAsync();
                        ViewData["cartcount"] = _context.ShoppingCarts.Count();
                        ViewBag.CartCount = ViewData["cartcount"];
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        result.Id = ser.Id + 1;
                        result.ProductDetailsId = ProductId;
                        result.ProductId = ProductId;
                        result.UserId = UserId;
                        result.ProductTypeId = ProductTypeId;
                        result.UnitPrice = UnitPrice;
                        result.TotalPrice = TotalPrice;
                        result.Quantity = Quantity;
                        _context.Add(result);
                        await _context.SaveChangesAsync();
                        ViewData["cartcount"] = _context.ShoppingCarts.Count();
                        ViewBag.CartCount = ViewData["cartcount"];
                        return RedirectToAction(nameof(Index));
                    }
                }

                
            }

            return RedirectToAction(nameof(Index));
            //return View(shoppingCart);
        }

        // GET: Products/Details/5
        [HttpPost]
        public async Task<IActionResult> AddToCart(int Id,int ProductId, int ProductTypeId, int UserId, int UnitPrice, int TotalPrice, int Quantity, ShoppingCart shoppingCart, int id = 0)
        {
            //may mali pa kapag nag start tayo uli ng bagong session di dumadagdag sa latest cart
            var productDetail = await _context.ProductDetails
                .Include(p => p.Product)
                .Include(p => p.ProductType)
                .FirstOrDefaultAsync(m => m.Id == Id);

IPT_101/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IPT_101</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.min.js" defer></script>
    <script type="text/javascript" src="~/EmailValidation.js" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/gsap.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" />
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.6/js/star-rating.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap-4.4.1.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IPT_101</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>

                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav text-right">

                        <li class="nav-item mt-2" id="cartmo">
                            
                        </li>


                        <li class="nav-item" id="name_mo">
                            <a class="nav-link text-dark" id="home_login_href" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IPT_101 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/popper.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

IPT_101/Views/Shared/_PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber="@Model.PageNumber"
          cs-paging-totalitems="@Model.TotalItems"
          cs-paging-pagesize="@Model.PageSize"
          cs-pagenumber-param="pagenumber"
          asp-route-sortOrder="@ViewBag.CurrentSortOrder"
          asp-controller=@ViewData["Controller"]
          asp-action=@ViewData["Action"]
          cs-pager-ul-class="pagination justify-content-center"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link">
          

</cs-pager>