IPT_101/Controllers/ShoppingCartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IPT_101.Repository;
using IPT_101.Repository.Models;

namespace IPT_101.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly IPT_101Context _context;

        public ShoppingCartsController(IPT_101Context context)
        {
            _context = context;
        }

        // GET: ShoppingCarts
        public async Task<IActionResult> Index()
        {
            var iPT_101Context = _context.ShoppingCarts.Include(s => s.Product).Include(s => s.ProductDetails).Include(s => s.ProductType).Include(s => s.User);
            return View(await iPT_101Context.ToListAsync());
        }
        [HttpPost]
        public async Task<PartialViewResult> ShoppingCartAsync(int Id)
        {
            List<ShoppingCart> sc = new List<ShoppingCart>();
            sc = await (from ShoppingCart in _context.ShoppingCarts
                        .Include(s => s.Product)
                        .Include(s => s.ProductDetails)
                        .Include(s => s.ProductType)
                        .Include(s => s.User)
                        .Where(p => p.UserId == Id)
                        select ShoppingCart).ToListAsync();
            var result = _context.ShoppingCarts
                             .Include(s => s.Product)
                             .Include(s => s.ProductDetails)
                             .Include(s => s.ProductType)
                             .Include(s => s.User)
                             .Where(p => p.UserId == Id);
            
            var ser = await _context.ShoppingCarts.Where(p => p.UserId == Id).ToListAsync();

            
            //ViewBag.CartCount = ser.Count();
            return PartialView("_Shopcart", sc);
        }
        [HttpPost]
        public async Task<IActionResult> Add(int Id, int UnitPrice)
        {

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.Product)
                .Include(s => s.ProductDetails)
                .Include(s => s.ProductType)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == Id);
            shoppingCart.Id = shoppingCart.Id;
            shoppingCart.ProductDetailsId = shoppingCart.ProductId;
            shoppingCart.ProductId = shoppingCart.ProductId;
            shoppingCart.UserId = shoppingCart.UserId;
            shoppingCart.ProductTypeId = shoppingCart.ProductTypeId;
            shoppingCart.UnitPrice = UnitPrice;
            shoppingCart.Quantity = shoppingCart.Quantity + 1;
            shoppingCart.TotalPrice = shoppingCart.TotalPrice + UnitPrice;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Minus(int Id, int UnitPrice)
        {

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.Product)
                .Include(s => s.ProductDetails)
                .Include(s => s.ProductType)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == Id);
            
            if(shoppingCart.Quantity > 1)
            {
                shoppingCart.Id = shoppingCart.Id;
                shoppingCart.ProductDetailsId = shoppingCart.ProductId;
                shoppingCart.ProductId = shoppingCart.ProductId;
                shoppingCart.UserId = shoppingCart.UserId;
                shoppingCart.ProductTypeId = shoppingCart.ProductTypeId;
                shoppingCart.UnitPrice = UnitPrice;
                shoppingCart.Quantity = shoppingCart.Quantity - 1;
                shoppingCart.TotalPrice = shoppingCart.TotalPrice - UnitPrice;
            }
            else
            {
                _context.ShoppingCarts.Remove(shoppingCart);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Alis(int Id)
        {

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.Product)
                .Include(s => s.ProductDetails)
                .Include(s => s.ProductType)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == Id);

            _context.ShoppingCarts.Remove(shoppingCart);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: ShoppingCarts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.Product)
                .Include(s => s.ProductDetails)
                .Include(s => s.ProductType)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "ProductCode");
            ViewData["ProductDetailsId"] = new SelectList(_context.ProductDetails, "Id", "AdditionalInfo");
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType1");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Address");
            return View();
        }

        // POST: ShoppingCarts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,ProductTypeId,ProductDetailsId,UserId,UnitPrice,TotalPrice,Quantity")] ShoppingCart shoppingCart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoppingCart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "ProductCode", shoppingCart.ProductId);
            ViewData["ProductDetailsId"] = new SelectList(_context.ProductDetails, "Id", "AdditionalInfo", shoppingCart.ProductDetailsId);
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType1", shoppingCart.ProductTypeId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Address", shoppingCart.UserId);
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts.FindAsync(id);
            if (shoppingCart == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "ProductCode", shoppingCart.ProductId);
            ViewData["ProductDetailsId"] = new SelectList(_context.ProductDetails, "Id", "AdditionalInfo", shoppingCart.ProductDetailsId);
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType1", shoppingCart.ProductTypeId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Address", shoppingCart.UserId);
            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,ProductTypeId,ProductDetailsId,UserId,UnitPrice,TotalPrice,Quantity")] ShoppingCart shoppingCart)
        {
            if (id != shoppingCart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoppingCart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoppingCartExists(shoppingCart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "ProductCode", shoppingCart.ProductId);
            ViewData["ProductDetailsId"] = new SelectList(_context.ProductDetails, "Id", "AdditionalInfo", shoppingCart.ProductDetailsId);
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType1", shoppingCart.ProductTypeId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Address", shoppingCart.UserId);
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.Product)
                .Include(s => s.ProductDetails)

IPT_101/Views/ShoppingCarts/Create.cshtml
@model IPT_101.Repository.Models.ShoppingCart

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label"></label>
                <select asp-for="ProductTypeId" class ="form-control" asp-items="ViewBag.ProductTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductDetailsId" class="control-label"></label>
                <select asp-for="ProductDetailsId" class ="form-control" asp-items="ViewBag.ProductDetailsId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IPT_101/Views/ShoppingCarts/Delete.cshtml
@model IPT_101.Repository.Models.ShoppingCart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductCode)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDetails)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDetails.AdditionalInfo)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductType.ProductType1)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Address)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IPT_101/Views/ShoppingCarts/Details.cshtml
@model IPT_101.Repository.Models.ShoppingCart

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDetails)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDetails.AdditionalInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductType.ProductType1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IPT_101/Views/ShoppingCarts/Edit.cshtml
@model IPT_101.Repository.Models.ShoppingCart

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label"></label>
                <select asp-for="ProductTypeId" class="form-control" asp-items="ViewBag.ProductTypeId"></select>
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDetailsId" class="control-label"></label>
                <select asp-for="ProductDetailsId" class="form-control" asp-items="ViewBag.ProductDetailsId"></select>
                <span asp-validation-for="ProductDetailsId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IPT_101/Views/ShoppingCarts/Index.cshtml
@model IEnumerable<IPT_101.Repository.Models.ShoppingCart>

@{
    ViewData["Title"] = "Index";
}

<h1>Shopping Cart</h1>
<div id="sarsoxer">
    
</div>
<script>
    $("#cartmo").hide();
    mySessionData = JSON.parse(sessionStorage.getItem("myAccountStorage"));
        $(() => {
        //ilagay sa data ang userid tapos ibabalik niya sa controller ng shoppingcarts tapos ibabalik ng shoppingcarts yung data niya sa shoppingcarts okay
            $.ajax({
                url: '@Url.Action("ShoppingCart", "ShoppingCarts")',
                datatype: 'html',
                method: 'POST',
                data: { Id: mySessionData.id },
                success: (res) => {
                    console.log("res", res);
                    $("#sarsoxer").append(res);

                },
                error: (err) => {
                    console.log(err);
                }
            });
    });
</script>

IPT_101/Views/ShoppingCarts/_Shopcart.cshtml
@model List<IPT_101.Repository.Models.ShoppingCart>

@if (Model.Count() != 0)
{

<div class="container" id="sarsoxer">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Product
                                </th>
                                <th>
                                    Unit Price
                                </th>
                                <th>
                                    Quantity
                                </th>
                                <th>
                                    SubTotal
                                </th>
                                <th>

                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <div class="row">
                                            <div class="mr-5">
                                                <a asp-action="Details" asp-controller="Products" asp-route-id="@item.ProductId">
                                                    <div class="card">
                                                        <img width="100" height="100" src="@item.ProductDetails.Image1" sizes="(max-width: 250px) 100vw, 250px">
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="mr-5"><br /> <a class="text-dark font-weight-bold" asp-action="Details" asp-controller="Products" asp-route-id="@item.ProductId">@item.Product.ProductName</a></div>
                                        </div>
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.UnitPrice)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TotalPrice)
                                    </td>
                                    <td>
                                        <input type="hidden" id="id_item_percart_@item.Id" value="@item.Id" />
                                        <input type="hidden" id="id_item_percart_unitprice_@item.Id" value="@item.UnitPrice" />
                                        <a class="btn btn-success mt-2" id="dagdagkpa_@item.Id" asp-action="Index"><span class="fa fa-plus general_icon text-white"></span></a>
                                        <a class="btn btn-danger mt-2" id="bawaskpa_@item.Id" asp-action="Index"><span class="fa fa-minus general_icon text-white"></span></a>
                                        <a class="btn btn-secondary mt-2" id="aliskpa_@item.Id" asp-action="Index"><span class="fa fa-trash general_icon text-white"></span></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <hr />
                </div>
            </div>
            
        </div>
        
        <div class="row">
            <div class="col-12">
                <div class="card-body text-right">
                        
                    <a class="btn btn-secondary" href="/checkout">Proceed to Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>
}
else
{
    <div class="text-center">Your cart is empty!</div>
    <br />
}
<script>
    $mySessionData = JSON.parse(sessionStorage.getItem("myAccountStorage"));
    $("#cartmo").hide();
    getCartCount();
    function getCartCount() {
        $(() => {
        //ilagay sa data ang userid tapos ibabalik niya sa controller ng shoppingcarts tapos ibabalik ng shoppingcarts yung data niya sa shoppingcarts okay
            $.ajax({
                url: '@Url.Action("CartCount", "Home")',
                datatype: 'html',
                method: 'POST',
                data: { Id: $mySessionData.id },
                success: (res) => {
                    console.log("res", res);
                    $("#sarsoxer").append(res);

                },
                error: (err) => {
                    console.log(err);
                }
            });
    });
    }

    for (let i = 0; i < 50; i++) {
        $("#dagdagkpa_"+i).on("click", () => {
        $.ajax({
                url: '@Url.Action("Add", "ShoppingCarts")',
                //datatype: 'html',
                method: 'POST',
                data: {
                    Id: $("#id_item_percart_"+i).val(),
                    UnitPrice: $("#id_item_percart_unitprice_"+i).val()
                },
                success: (res) => {
                    console.log("res", res);

                    getCartCount();
                },
                error: (err) => {
                    console.log("err", err);
                }

            });

    });
    }

    for (let i = 0; i < 50; i++) {
        $("#bawaskpa_"+i).on("click", () => {
        $.ajax({
                url: '@Url.Action("Minus", "ShoppingCarts")',
                //datatype: 'html',
                method: 'POST',
                data: {
                    Id: $("#id_item_percart_"+i).val(),
                    UnitPrice: $("#id_item_percart_unitprice_"+i).val()
                },
                success: (res) => {
                    //console.log("res", res);

                    getCartCount();
                },
                error: (err) => {
                    console.log("err", err);
                }

            });

    });
    }

    for (let i = 0; i < 50; i++) {
        $("#aliskpa_"+i).on("click", () => {
        $.ajax({
                url: '@Url.Action("Alis", "ShoppingCarts")',
                //datatype: 'html',
                method: 'POST',
                data: {
                    Id: $("#id_item_percart_"+i).val()
                },
                success: (res) => {
                    //console.log("res", res);

                    getCartCount();
                },
                error: (err) => {
                    console.log("err", err);
                }

            });

    });
    }
</script>